# Generated by Django 3.2.2 on 2021-06-29 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
